apiVersion: batch/v1
kind: Job
metadata:
  name: stress-cpu
spec:
  template:
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args: ["--cpu", "2", "--timeout", "300s"]
      restartPolicy: Never
